export interface Profesionel{
    id?: number,
    name: string,
    formJurdique: string,
    siret: string,
    nafApe: string,
    phone: string,
    email: string,
    webSite: string,
    postalAddress: string,
    fullAddress: string,
    zip: number,
    country: string,
    state: string,
    diriEntreprise: string,
    img: any,
    description: string,
    notes: string,
    exceptDiscount: string,
    totalInvoice: number,
    initialReview: number,
    documents: any[],
    password: string
}